# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "emoticons_helper"
  s.version = "0.2.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["gravindra"]
  s.date = "2013-08-31"
  s.description = "Gives face to your text."
  s.email = "ravighare26@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "emoticons_helper.gemspec",
    "lib/emoticons_helper.rb",
    "lib/generators/smile_generator.rb",
    "lib/generators/templates/smileys.rb",
    "lib/generators/templates/smilies.css",
    "lib/generators/templates/smilies.yml",
    "lib/generators/templates/smilies/angry.gif",
    "lib/generators/templates/smilies/bigsmile.gif",
    "lib/generators/templates/smilies/cool.gif",
    "lib/generators/templates/smilies/dull.gif",
    "lib/generators/templates/smilies/evilgrin.gif",
    "lib/generators/templates/smilies/no.gif",
    "lib/generators/templates/smilies/rofl.gif",
    "lib/generators/templates/smilies/sadsmile.gif",
    "lib/generators/templates/smilies/sleepy.gif",
    "lib/generators/templates/smilies/smile.gif",
    "lib/generators/templates/smilies/smilies-sprite.png",
    "lib/generators/templates/smilies/tongueout.gif",
    "lib/generators/templates/smilies/wink.gif",
    "lib/generators/templates/smilies/wondering.gif",
    "lib/generators/templates/smilies/worried.gif",
    "lib/generators/templates/smilies/yes.gif",
    "test/helper.rb",
    "test/test_emoticons_helper.rb"
  ]
  s.homepage = "http://github.com/gravindra/emoticons_helper"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.25"
  s.summary = "This Gem Rocks ..."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

